version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: health-food-container
    restart: always
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
volumes:
  postgres:
